[2023-04-10T16:29:33.770+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v04.postgres_to_s3 manual__2023-04-10T16:07:13.365557+00:00 [queued]>
[2023-04-10T16:29:33.782+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_postgres_hooks_v04.postgres_to_s3 manual__2023-04-10T16:07:13.365557+00:00 [queued]>
[2023-04-10T16:29:33.782+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T16:29:33.782+0000] {taskinstance.py:1289} INFO - Starting attempt 6 of 11
[2023-04-10T16:29:33.783+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-10T16:29:33.806+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): postgres_to_s3> on 2023-04-10 16:07:13.365557+00:00
[2023-04-10T16:29:33.809+0000] {standard_task_runner.py:55} INFO - Started process 3331 to run task
[2023-04-10T16:29:33.811+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_postgres_hooks_v04', 'postgres_to_s3', 'manual__2023-04-10T16:07:13.365557+00:00', '--job-id', '7153', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_postgress_hooks.py', '--cfg-path', '/tmp/tmpnl6peq1y']
[2023-04-10T16:29:33.814+0000] {standard_task_runner.py:83} INFO - Job 7153: Subtask postgres_to_s3
[2023-04-10T16:29:33.883+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_postgres_hooks_v04.postgres_to_s3 manual__2023-04-10T16:07:13.365557+00:00 [running]> on host d034b084d02f
[2023-04-10T16:29:33.984+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=coder2j
AIRFLOW_CTX_DAG_ID=dag_with_postgres_hooks_v04
AIRFLOW_CTX_TASK_ID=postgres_to_s3
AIRFLOW_CTX_EXECUTION_DATE=2023-04-10T16:07:13.365557+00:00
AIRFLOW_CTX_TRY_NUMBER=6
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-10T16:07:13.365557+00:00
[2023-04-10T16:29:33.987+0000] {logging_mixin.py:137} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:205 AirflowContextDeprecationWarning: Accessing 'next_ds_nodash' from the template is deprecated and will be removed in a future version. Please use '{{ data_interval_end | ds_nodash }}' instead.
[2023-04-10T16:29:33.996+0000] {base.py:73} INFO - Using connection ID 'postgres_localhost' for task execution.
[2023-04-10T16:29:34.001+0000] {dag_with_postgress_hooks.py:34} INFO - Saved orders data in text file: dags/get_orders_20230410.txt
[2023-04-10T16:29:34.001+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_postgress_hooks.py", line 36, in postgres_to_s3
    s3_hook = S3Hook(aws_conn_id="minio_conn", wildcard_match=False)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/amazon/aws/hooks/s3.py", line 162, in __init__
    super().__init__(*args, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'wildcard_match'
[2023-04-10T16:29:34.009+0000] {taskinstance.py:1332} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_with_postgres_hooks_v04, task_id=postgres_to_s3, execution_date=20230410T160713, start_date=20230410T162933, end_date=20230410T162934
[2023-04-10T16:29:34.021+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 7153 for task postgres_to_s3 (__init__() got an unexpected keyword argument 'wildcard_match'; 3331)
[2023-04-10T16:29:34.066+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-10T16:29:34.090+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
