[2023-04-07T15:04:00.439+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependancies_v02.get_matplotlib scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-07T15:04:00.459+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependancies_v02.get_matplotlib scheduled__2023-04-03T00:00:00+00:00 [queued]>
[2023-04-07T15:04:00.459+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T15:04:00.459+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-07T15:04:00.459+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T15:04:00.489+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2023-04-03 00:00:00+00:00
[2023-04-07T15:04:00.499+0000] {standard_task_runner.py:55} INFO - Started process 2549 to run task
[2023-04-07T15:04:00.504+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependancies_v02', 'get_matplotlib', 'scheduled__2023-04-03T00:00:00+00:00', '--job-id', '6893', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependancies.py', '--cfg-path', '/tmp/tmphxt08tiu']
[2023-04-07T15:04:00.505+0000] {standard_task_runner.py:83} INFO - Job 6893: Subtask get_matplotlib
[2023-04-07T15:04:00.623+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_python_dependancies_v02.get_matplotlib scheduled__2023-04-03T00:00:00+00:00 [running]> on host fdb83a86d851
[2023-04-07T15:04:00.745+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=dag_with_python_dependancies_v02
AIRFLOW_CTX_TASK_ID=get_matplotlib
AIRFLOW_CTX_EXECUTION_DATE=2023-04-03T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-04-03T00:00:00+00:00
[2023-04-07T15:04:00.747+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependancies.py", line 18, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2023-04-07T15:04:00.757+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=dag_with_python_dependancies_v02, task_id=get_matplotlib, execution_date=20230403T000000, start_date=20230407T150400, end_date=20230407T150400
[2023-04-07T15:04:00.777+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6893 for task get_matplotlib (No module named 'matplotlib'; 2549)
[2023-04-07T15:04:00.804+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-07T15:04:00.844+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
