[2023-04-07T15:04:02.448+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_python_dependancies_v02.get_matplotlib manual__2023-04-07T15:03:57.939155+00:00 [queued]>
[2023-04-07T15:04:02.457+0000] {taskinstance.py:1090} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_python_dependancies_v02.get_matplotlib manual__2023-04-07T15:03:57.939155+00:00 [queued]>
[2023-04-07T15:04:02.457+0000] {taskinstance.py:1288} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T15:04:02.457+0000] {taskinstance.py:1289} INFO - Starting attempt 1 of 1
[2023-04-07T15:04:02.458+0000] {taskinstance.py:1290} INFO - 
--------------------------------------------------------------------------------
[2023-04-07T15:04:02.480+0000] {taskinstance.py:1309} INFO - Executing <Task(PythonOperator): get_matplotlib> on 2023-04-07 15:03:57.939155+00:00
[2023-04-07T15:04:02.484+0000] {standard_task_runner.py:55} INFO - Started process 2556 to run task
[2023-04-07T15:04:02.486+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_with_python_dependancies_v02', 'get_matplotlib', 'manual__2023-04-07T15:03:57.939155+00:00', '--job-id', '6896', '--raw', '--subdir', 'DAGS_FOLDER/dag_with_python_dependancies.py', '--cfg-path', '/tmp/tmpvumwv152']
[2023-04-07T15:04:02.487+0000] {standard_task_runner.py:83} INFO - Job 6896: Subtask get_matplotlib
[2023-04-07T15:04:02.545+0000] {task_command.py:389} INFO - Running <TaskInstance: dag_with_python_dependancies_v02.get_matplotlib manual__2023-04-07T15:03:57.939155+00:00 [running]> on host fdb83a86d851
[2023-04-07T15:04:02.634+0000] {taskinstance.py:1518} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=dejan
AIRFLOW_CTX_DAG_ID=dag_with_python_dependancies_v02
AIRFLOW_CTX_TASK_ID=get_matplotlib
AIRFLOW_CTX_EXECUTION_DATE=2023-04-07T15:03:57.939155+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-04-07T15:03:57.939155+00:00
[2023-04-07T15:04:02.636+0000] {taskinstance.py:1776} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_with_python_dependancies.py", line 18, in get_matplotlib
    import matplotlib
ModuleNotFoundError: No module named 'matplotlib'
[2023-04-07T15:04:02.644+0000] {taskinstance.py:1332} INFO - Marking task as FAILED. dag_id=dag_with_python_dependancies_v02, task_id=get_matplotlib, execution_date=20230407T150357, start_date=20230407T150402, end_date=20230407T150402
[2023-04-07T15:04:02.655+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 6896 for task get_matplotlib (No module named 'matplotlib'; 2556)
[2023-04-07T15:04:02.664+0000] {local_task_job.py:212} INFO - Task exited with return code 1
[2023-04-07T15:04:02.687+0000] {taskinstance.py:2596} INFO - 0 downstream tasks scheduled from follow-on schedule check
